# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" , "docker-test"]

env:
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      # TODO pass artifacts to docker build
      run: mvn --batch-mode clean verify
    # TODO put these in a script and link them
    - name: Build AMD64 Docker
      run: mvn --batch-mode jib:build -Djib.from.platforms[0].architecture=amd64 -Djib.to.auth.username=DOCKER_HUB_USER -Djib.to.auth.password=$DOCKER_HUB_KEY
    - name: Build ARM64 Docker
      run: mvn --batch-mode jib:build -Djib.from.platforms[0].architecture=arm64 -Djib.to.auth.username=DOCKER_HUB_USER -Djib.to.auth.password=$DOCKER_HUB_KEY